services:
  - type: web
    name: ai-resume-analyzer
    env: python
    plan: free
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.address 0.0.0.0 --server.port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
